name: Test Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: feat,fix,chore

      - uses: step-security/skip-duplicate-actions@v5
        with:
          do_not_skip: '["release"]'

      - uses: chetan/git-restore-mtime-action@v1
        with:
          pattern: '**/*'
          
      - uses: tj-actions/changed-files@v38
      - uses: step-security/changed-files@v47

      # commit sha test 
      - uses: tj-actions/changed-files@17f3fec1edef0c3916d59cbcee1585fcd457e456 # v38.0.0
      - uses: step-security/changed-files@v47

  lint3:
    runs-on: ubuntu-latest-code
    steps:
      - uses: actions/checkout@v1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

      - uses: step-security/s3-actions-cache/restore@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ✅ Simplified Checkov step (no name, no id)
      - uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif

      - uses: step-security/google-github-auth@v2
      - uses: hashicorp/setup-terraform@v3
      - uses: step-security/mise-action@v4
      - uses: jdx/mise-action@v4
      - uses: step-security/arduino-setup-task@v3
      - uses: JarvusInnovations/background-action@v1
      - uses: step-security/buf-action@v1
      

  lint2:
    runs-on: ubuntu-latest-code
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout-test@v1

  lint5:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

  lint6:
    runs-on: gpu-rtx-5050
    steps:
      - uses: actions/checkout@v1
      
  build2:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - uses: actions/checkout@v3
      - run: echo "build"
      
  
